version: "3"

services:
  vote:
    build: ./vote
    command: python app.py
  result:
    build: ./result
    command: nodemon --debug server.js
  worker:
    build:
      context: ./worker
  redis:
    image: redis:alpine
    container_name: redis
  db:
    image: postgres:9.4
    container_name: db
